// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqjgEMCKTMPzxRfyvZU67inVtDbifu_fs',
    appId: '1:868206167292:web:54e15abc1d72c57af28379',
    messagingSenderId: '868206167292',
    projectId: 'project2201a',
    authDomain: 'project2201a.firebaseapp.com',
    databaseURL: 'https://project2201a-default-rtdb.firebaseio.com',
    storageBucket: 'project2201a.appspot.com',
    measurementId: 'G-8LZ5SFXCJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH7MwOtiW5z1aPlXefSJATQU3nlbJjQQw',
    appId: '1:868206167292:android:091b23cbb5ccd3bdf28379',
    messagingSenderId: '868206167292',
    projectId: 'project2201a',
    databaseURL: 'https://project2201a-default-rtdb.firebaseio.com',
    storageBucket: 'project2201a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxe0OkUTZtfjtfNCchjJm9-PzP0CHBdOY',
    appId: '1:868206167292:ios:d5490b604001b932f28379',
    messagingSenderId: '868206167292',
    projectId: 'project2201a',
    databaseURL: 'https://project2201a-default-rtdb.firebaseio.com',
    storageBucket: 'project2201a.appspot.com',
    iosBundleId: 'com.example.flutterTodos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxe0OkUTZtfjtfNCchjJm9-PzP0CHBdOY',
    appId: '1:868206167292:ios:d5490b604001b932f28379',
    messagingSenderId: '868206167292',
    projectId: 'project2201a',
    databaseURL: 'https://project2201a-default-rtdb.firebaseio.com',
    storageBucket: 'project2201a.appspot.com',
    iosBundleId: 'com.example.flutterTodos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqjgEMCKTMPzxRfyvZU67inVtDbifu_fs',
    appId: '1:868206167292:web:d504b24d26187277f28379',
    messagingSenderId: '868206167292',
    projectId: 'project2201a',
    authDomain: 'project2201a.firebaseapp.com',
    databaseURL: 'https://project2201a-default-rtdb.firebaseio.com',
    storageBucket: 'project2201a.appspot.com',
    measurementId: 'G-HEQ5RGDZ4P',
  );

}